### ISSUE TITLE
Advice or plugin recommendation

### ISSUE THREAD

**Issue by Razgort** [alexzuza/angular-plugin-architecture#3]
Hello guys,
I'm very interesting in your project.
In fact i'm building for my company a large application.
This app is based on asp core and angular 7.
But we want this app to be extensible on the backend part AND on the front (angular) part.
Because we will publish this app compiled and give it to our integrators that will want to do their own specific development around our app. I'm not sure if i'm understandable.
Ask me if not.

But anyway in our study case would you recommand we use your framework for the front end part ?
We are looking for the Extcore extension for the backend part, are you compatible with it ?
Also we will migrate to asp core 3.0 once it will be in release. Do you have plans for supporting it ?

Thanks in advance,
Alexandre MOULAY

**Comment by AlexCoderBit** [comment]
Subscribed ))
Very interested in further development of such 'plugable' approach. 
What are your plans for future of this project?
I'd love to help in case you are interested in integrating with Redux state management.

**Comment by Razgort** [comment]
Hi guys, trying some play around your solution i tried adding json configuration in the shared module but i got this error when import :
BUILD ERROR
Unexpected token / in JSON at position 0
SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.transform (F:\angular-plugin-architecture\node_modules\rollup-plugin-json\dist\rollup-plugin-json.cjs.js:18:20)
    at F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:20962:25
    at <anonymous>

Unexpected token / in JSON at position 0
SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.transform (F:\angular-plugin-architecture\node_modules\rollup-plugin-json\dist\rollup-plugin-json.cjs.js:18:20)
    at F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:20962:25
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-plugin-architecture@0.0.0 build:shared: `ng build shared && ng build --project plugins --prod --modulePath=shared#SharedModule --pluginName=shared  --outputPath=./src/assets/plugins`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-plugin-architecture@0.0.0 build:shared script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\a.moulay\AppData\Roaming\npm-cache\_logs\2019-06-04T12_11_57_962Z-debug.log

DO you have any idea why ?

**Comment by Razgort** [comment]
Okay some improvements here i managed to get through this error above but now i have the following ..
Building Angular Package
Building entry point 'shared'
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
Error: Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
    at error (F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:3460:30)
    at F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:21474:17
    at <anonymous>

Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
Error: Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
    at error (F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:3460:30)
    at F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:21474:17

It seems shared.js entry point not found ?
